title: univzor
email: otobrglez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "univizor.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
# repository: univizor/univizor.github.io

sass:
  sass_dir: _sass

authors:
  -
    name: "Oto Brglez"
    github_url: https://github.com/otobrglez
    linkedin_url: https://www.linkedin.com/in/otobrglez
    twitter_url: https://twitter.com/otobrglez
    email: otobrglez@gmail.com
  -
    name: "Jožko Škrablin"
    github_url: https://github.com/jozko
    linkedin_url: https://www.linkedin.com/in/jozko-skrablin-75588757
    twitter_url: https://twitter.com/jskrablin
    email: jozko@zomg.si

gems:
  - jekyll-gravatar
